//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Alignment : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean SingleSelect
        {
            get
            {
                return SteamVR_Actions.alignment_SingleSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleSelect
        {
            get
            {
                return SteamVR_Actions.alignment_ToggleSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.alignment_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Undo
        {
            get
            {
                return SteamVR_Actions.alignment_Undo;
            }
        }
        
        public virtual SteamVR_Action_Boolean Redo
        {
            get
            {
                return SteamVR_Actions.alignment_Redo;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHand
        {
            get
            {
                return SteamVR_Actions.alignment_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHand
        {
            get
            {
                return SteamVR_Actions.alignment_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.alignment_Haptic;
            }
        }
    }
}
