//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Alignment : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean SingleSelect
        {
            get
            {
                return SteamVR_Actions.alignment_SingleSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleSelect
        {
            get
            {
                return SteamVR_Actions.alignment_ToggleSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.alignment_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Left
        {
            get
            {
                return SteamVR_Actions.alignment_D_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Right
        {
            get
            {
                return SteamVR_Actions.alignment_D_Right;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHand
        {
            get
            {
                return SteamVR_Actions.alignment_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHand
        {
            get
            {
                return SteamVR_Actions.alignment_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean TakeGizmo
        {
            get
            {
                return SteamVR_Actions.alignment_TakeGizmo;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.alignment_Menu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Analog
        {
            get
            {
                return SteamVR_Actions.alignment_Analog;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Up
        {
            get
            {
                return SteamVR_Actions.alignment_D_Up;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Down
        {
            get
            {
                return SteamVR_Actions.alignment_D_Down;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.alignment_Haptic;
            }
        }
    }
}
